package com.owen233666.datagen;/*
 * XHeYa's Furniture (xhe_furniture) - All Rights Reserved
 *
 * Copyright (C) 2026 owen233666, XHeYa_3u3
 */
// Generated by `runDatagen` (see common.gradle). Mirrors the hand-written tag under
// src/main/resources; keep both in sync when editing by hand.
//#if FABRIC
//$$ package com.owen233666.datagen;
//$$
//$$ import com.owen233666.block.ModBlocks;
//$$ import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
//$$ import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
//$$ import net.minecraft.core.HolderLookup;
//$$ import net.minecraft.tags.BlockTags;
//$$ import net.minecraft.world.level.block.Block;
//$$
//$$ import java.util.concurrent.CompletableFuture;
//$$
//$$ public class ModBlockTagProvider extends FabricTagProvider.BlockTagProvider {
//$$
//$$     public ModBlockTagProvider(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
//$$         super(output, registriesFuture);
//$$     }
//$$
//$$     @Override
//$$     protected void addTags(HolderLookup.Provider arg) {
//$$         getOrCreateTagBuilder(BlockTags.MINEABLE_WITH_AXE)
//$$                 .add(
//$$                         ModBlocks.EASEL.get(),
//$$                         ModBlocks.CANVAS.get(),
//$$                         ModBlocks.DRAWING_BOARD.get(),
//$$                         ModBlocks.GRID_SHELF_OAK.get(),
//$$                         ModBlocks.GRID_SHELF_SPRUCE.get(),
//$$                         ModBlocks.GRID_SHELF_JUNGLE.get(),
//$$                         ModBlocks.GRID_SHELF_BIRCH.get(),
//$$                         ModBlocks.GRID_SHELF_ACACIA.get(),
//$$                         ModBlocks.GRID_SHELF_DARK_OAK.get(),
//$$                         ModBlocks.GRID_SHELF_MANGROVE.get(),
//$$                         ModBlocks.GRID_SHELF_CHERRY.get(),
//$$                         ModBlocks.GRID_SHELF_BAMBOO.get(),
//$$                         ModBlocks.GRID_SHELF_PALE_OAK.get(),
//$$                         ModBlocks.GRID_SHELF_BLACKSTONE.get()
//$$                 );
//$$
//$$         // The furniture crafting tables are wooden, so an axe mines them quickly.
//$$         getOrCreateTagBuilder(BlockTags.MINEABLE_WITH_AXE)
//$$                 .add(ModBlocks.craftingTableBlocks().toArray(new Block[0]));
//$$     }
//$$ }
//$$
//#endif