package com.owen233666.datagen;/*
 * XHeYa's Furniture (xhe_furniture) - All Rights Reserved
 *
 * Copyright (C) 2026 owen233666, XHeYa_3u3
 */
// Generated by `runDatagen` (see common.gradle). Mirrors the hand-written loot tables under
// src/main/resources/data/xhe_furniture/loot_table; keep both in sync when editing by hand.
//
// The blocks below are deliberately split instead of nested: a `//#if` that is already inside
// another `//#if` would have to carry a `//$$` of its own, so the version dependent parts are
// expressed as sibling top level conditions instead.
//#if FABRIC
//$$ package com.owen233666.datagen;
//$$
//$$ import com.owen233666.block.ModBlocks;
//$$ import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
//$$ import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
//#endif
//#if FABRIC && MC >= 12005
//$$ import net.minecraft.core.HolderLookup;
//$$
//$$ import java.util.concurrent.CompletableFuture;
//#endif
//#if FABRIC
//$$
//$$ public class ModBlockLootTableProvider extends FabricBlockLootTableProvider {
//#endif
//#if FABRIC && MC >= 12005
//$$
//$$     public ModBlockLootTableProvider(FabricDataOutput dataOutput, CompletableFuture<HolderLookup.Provider> registriesFuture) {
//$$         super(dataOutput, registriesFuture);
//$$     }
//#endif
//#if FABRIC && MC < 12005
//$$
//$$     public ModBlockLootTableProvider(FabricDataOutput dataOutput) {
//$$         super(dataOutput);
//$$     }
//#endif
//#if FABRIC
//$$
//$$     @Override
//$$     public void generate() {
//$$         //Cups
//$$         dropSelf(ModBlocks.HOT_COCOA.get());
//$$         //Shoe Flowerpots
//$$         dropSelf(ModBlocks.WHITE_SHOE_FLOWERPOT.get());
//$$         dropSelf(ModBlocks.PINK_SHOE_FLOWERPOT.get());
//$$         dropSelf(ModBlocks.RED_SHOE_FLOWERPOT.get());
//$$         dropSelf(ModBlocks.GREEN_SHOE_FLOWERPOT.get());
//$$         dropSelf(ModBlocks.YELLOW_SHOE_FLOWERPOT.get());
//$$         //Slippers
//$$         dropSelf(ModBlocks.WHITE_BUNNY_SLIPPERS.get());
//$$         dropSelf(ModBlocks.WHITE_HAMSTERS_SLIPPERS.get());
//$$         dropSelf(ModBlocks.WHITE_BEAR_SLIPPERS.get());
//$$         dropSelf(ModBlocks.BEIGE_BUNNY_SLIPPERS.get());
//$$         dropSelf(ModBlocks.BEIGE_HAMSTERS_SLIPPERS.get());
//$$         dropSelf(ModBlocks.BEIGE_BEAR_SLIPPERS.get());
//$$         dropSelf(ModBlocks.BROWN_BUNNY_SLIPPERS.get());
//$$         dropSelf(ModBlocks.BROWN_HAMSTERS_SLIPPERS.get());
//$$         dropSelf(ModBlocks.BROWN_BEAR_SLIPPERS.get());
//$$         dropSelf(ModBlocks.BLACK_BUNNY_SLIPPERS.get());
//$$         dropSelf(ModBlocks.BLACK_HAMSTERS_SLIPPERS.get());
//$$         dropSelf(ModBlocks.BLACK_BEAR_SLIPPERS.get());
//$$         dropSelf(ModBlocks.CALICO_BUNNY_SLIPPERS.get());
//$$         dropSelf(ModBlocks.CALICO_HAMSTERS_SLIPPERS.get());
//$$         dropSelf(ModBlocks.PANDA_SLIPPERS.get());
//$$         //Carpets
//$$         dropSelf(ModBlocks.CARPET_BLACK.get());
//$$         dropSelf(ModBlocks.CARPET_BLACK_A.get());
//$$         dropSelf(ModBlocks.CARPET_BLUE.get());
//$$         dropSelf(ModBlocks.CARPET_BLUE_A.get());
//$$         dropSelf(ModBlocks.CARPET_BLUE_B.get());
//$$         dropSelf(ModBlocks.CARPET_BROWN.get());
//$$         dropSelf(ModBlocks.CARPET_BROWN_A.get());
//$$         dropSelf(ModBlocks.CARPET_DEEP_BLUE.get());
//$$         dropSelf(ModBlocks.CARPET_DEEP_BLUE_A.get());
//$$         dropSelf(ModBlocks.CARPET_DEEP_BLUE_B.get());
//$$         dropSelf(ModBlocks.CARPET_DEEP_GREEN.get());
//$$         dropSelf(ModBlocks.CARPET_DEEP_GREEN_A.get());
//$$         dropSelf(ModBlocks.CARPET_DEEP_PURPLE.get());
//$$         dropSelf(ModBlocks.CARPET_DEEP_PURPLE_A.get());
//$$         dropSelf(ModBlocks.CARPET_FLAPJACK.get());
//$$         dropSelf(ModBlocks.CARPET_FLAPJACK_A.get());
//$$         dropSelf(ModBlocks.CARPET_GRAY.get());
//$$         dropSelf(ModBlocks.CARPET_GRAY_A.get());
//$$         dropSelf(ModBlocks.CARPET_GREEN.get());
//$$         dropSelf(ModBlocks.CARPET_GREEN_A.get());
//$$         dropSelf(ModBlocks.CARPET_LEMON_SLICE.get());
//$$         dropSelf(ModBlocks.CARPET_ORANGE.get());
//$$         dropSelf(ModBlocks.CARPET_ORANGE_A.get());
//$$         dropSelf(ModBlocks.CARPET_PINK.get());
//$$         dropSelf(ModBlocks.CARPET_PINK_A.get());
//$$         dropSelf(ModBlocks.CARPET_PINK_B.get());
//$$         dropSelf(ModBlocks.CARPET_PIZZA.get());
//$$         dropSelf(ModBlocks.CARPET_PURPLE.get());
//$$         dropSelf(ModBlocks.CARPET_PURPLE_A.get());
//$$         dropSelf(ModBlocks.CARPET_RED.get());
//$$         dropSelf(ModBlocks.CARPET_RED_A.get());
//$$         dropSelf(ModBlocks.CARPET_WAFFLE.get());
//$$         dropSelf(ModBlocks.CARPET_WAFFLE_A.get());
//$$         dropSelf(ModBlocks.CARPET_WHITE.get());
//$$         dropSelf(ModBlocks.CARPET_WHITE_A.get());
//$$         dropSelf(ModBlocks.CARPET_YELLOW.get());
//$$         //Rattan Table
//$$         dropSelf(ModBlocks.RATTAN_TABLE.get());
//$$         //Furniture Crafting Tables
//$$         dropSelf(ModBlocks.FURNITURE_CRAFTING_TABLE_OAK.get());
//$$         dropSelf(ModBlocks.FURNITURE_CRAFTING_TABLE_SPRUCE.get());
//$$         dropSelf(ModBlocks.FURNITURE_CRAFTING_TABLE_BIRCH.get());
//$$         dropSelf(ModBlocks.FURNITURE_CRAFTING_TABLE_JUNGLE.get());
//$$         dropSelf(ModBlocks.FURNITURE_CRAFTING_TABLE_ACACIA.get());
//$$         dropSelf(ModBlocks.FURNITURE_CRAFTING_TABLE_DARK_OAK.get());
//$$         dropSelf(ModBlocks.FURNITURE_CRAFTING_TABLE_MANGROVE.get());
//$$         dropSelf(ModBlocks.FURNITURE_CRAFTING_TABLE_CHERRY.get());
//$$         dropSelf(ModBlocks.FURNITURE_CRAFTING_TABLE_BAMBOO.get());
//$$         dropSelf(ModBlocks.FURNITURE_CRAFTING_TABLE_PALE_OAK.get());
//$$         dropSelf(ModBlocks.FURNITURE_CRAFTING_TABLE_BLACKSTONE.get());
//$$         //Painting Studio Series
//$$         dropSelf(ModBlocks.EASEL.get());
//$$         dropSelf(ModBlocks.CANVAS.get());
//$$         dropSelf(ModBlocks.DRAWING_BOARD.get());
//$$         dropSelf(ModBlocks.CANVAS_BIG.get());
//$$         dropSelf(ModBlocks.PAINTING_FRAME_OAK.get());
//$$         dropSelf(ModBlocks.PAINTING_FRAME_SPRUCE.get());
//$$         dropSelf(ModBlocks.PAINTING_FRAME_JUNGLE.get());
//$$         dropSelf(ModBlocks.PAINTING_FRAME_BIRCH.get());
//$$         dropSelf(ModBlocks.PAINTING_FRAME_ACACIA.get());
//$$         dropSelf(ModBlocks.PAINTING_FRAME_DARK_OAK.get());
//$$         dropSelf(ModBlocks.PAINTING_FRAME_MANGROVE.get());
//$$         dropSelf(ModBlocks.PAINTING_FRAME_CHERRY.get());
//$$         dropSelf(ModBlocks.PAINTING_FRAME_BAMBOO.get());
//$$         dropSelf(ModBlocks.PAINTING_FRAME_PALE_OAK.get());
//$$         dropSelf(ModBlocks.PAINTING_FRAME_BLACKSTONE.get());
//$$         dropSelf(ModBlocks.PHOTO_PAPER_WHITE_A.get());
//$$         dropSelf(ModBlocks.PHOTO_PAPER_WHITE_B.get());
//$$         dropSelf(ModBlocks.PHOTO_PAPER_WHITE_C.get());
//$$         dropSelf(ModBlocks.PHOTO_PAPER_BLACK_A.get());
//$$         dropSelf(ModBlocks.PHOTO_PAPER_BLACK_B.get());
//$$         dropSelf(ModBlocks.PHOTO_PAPER_BLACK_C.get());
//$$         dropSelf(ModBlocks.GRID_SHELF_OAK.get());
//$$         dropSelf(ModBlocks.GRID_SHELF_SPRUCE.get());
//$$         dropSelf(ModBlocks.GRID_SHELF_JUNGLE.get());
//$$         dropSelf(ModBlocks.GRID_SHELF_BIRCH.get());
//$$         dropSelf(ModBlocks.GRID_SHELF_ACACIA.get());
//$$         dropSelf(ModBlocks.GRID_SHELF_DARK_OAK.get());
//$$         dropSelf(ModBlocks.GRID_SHELF_MANGROVE.get());
//$$         dropSelf(ModBlocks.GRID_SHELF_CHERRY.get());
//$$         dropSelf(ModBlocks.GRID_SHELF_BAMBOO.get());
//$$         dropSelf(ModBlocks.GRID_SHELF_PALE_OAK.get());
//$$         dropSelf(ModBlocks.GRID_SHELF_BLACKSTONE.get());
//$$         dropSelf(ModBlocks.PAINT_BRUSH.get());
//$$         dropSelf(ModBlocks.PAINT_CAN.get());
//$$         dropSelf(ModBlocks.MESSY_PAINT_CAN.get());
//$$         dropSelf(ModBlocks.PAINT_BRUSH_BUCKET.get());
//$$         dropSelf(ModBlocks.CRAYON_BOX.get());
//$$         dropSelf(ModBlocks.PALETTE.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_LIGHT_OAK.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_LIGHT_SPRUCE.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_LIGHT_JUNGLE.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_LIGHT_BIRCH.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_LIGHT_ACACIA.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_LIGHT_DARK_OAK.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_LIGHT_MANGROVE.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_LIGHT_CHERRY.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_LIGHT_BAMBOO.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_LIGHT_PALE_OAK.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_LIGHT_BLACKSTONE.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_DARK_OAK.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_DARK_SPRUCE.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_DARK_JUNGLE.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_DARK_BIRCH.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_DARK_ACACIA.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_DARK_DARK_OAK.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_DARK_MANGROVE.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_DARK_CHERRY.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_DARK_BAMBOO.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_DARK_PALE_OAK.get());
//$$         dropSelf(ModBlocks.CORK_BOARD_DARK_BLACKSTONE.get());
//$$     }
//$$ }
//#endif
