package com.owen233666.datagen;/*
 * XHeYa's Furniture (xhe_furniture) - All Rights Reserved
 *
 * Copyright (C) 2026 owen233666, XHeYa_3u3
 */
// Generated by `runDatagen` (see common.gradle). Mirrors the hand-written item tags under
// src/main/resources/data/xhe_furniture/tags/item; keep both in sync when editing by hand.
//#if FABRIC
//$$ package com.owen233666.datagen;
//$$
//$$ import com.owen233666.item.ModItemTags;
//$$ import com.owen233666.item.ModItems;
//$$ import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
//$$ import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
//$$ import net.minecraft.core.HolderLookup;
//$$
//$$ import java.util.concurrent.CompletableFuture;
//$$
//$$
//$$ public class ModItemTagProvider extends FabricTagProvider.ItemTagProvider {
//$$
//$$     public ModItemTagProvider(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> completableFuture) {
//$$         super(output, completableFuture);
//$$     }
//$$
//$$     @Override
//$$     protected void addTags(HolderLookup.Provider arg) {
//$$
//$$
//$$         getOrCreateTagBuilder(ModItemTags.PAINTINGS)
//$$                 .add(ModItems.PAINTING_ANGEL.get())
//$$                 .add(ModItems.PAINTING_BEDROOM_BED.get())
//$$                 .add(ModItems.PAINTING_BERRY_BUSH.get())
//$$                 .add(ModItems.PAINTING_BICHON.get())
//$$                 .add(ModItems.PAINTING_CAKE.get())
//$$                 .add(ModItems.PAINTING_CAT_UNDER_A_TREE.get())
//$$                 .add(ModItems.PAINTING_CHIME.get())
//$$                 .add(ModItems.PAINTING_CITY_NIGHT.get())
//$$                 .add(ModItems.PAINTING_CLOVER.get())
//$$                 .add(ModItems.PAINTING_COW.get())
//$$                 .add(ModItems.PAINTING_CRYSTAL_FAIRY.get())
//$$                 .add(ModItems.PAINTING_DESSERT.get())
//$$                 .add(ModItems.PAINTING_FLOWER_BASKET.get())
//$$                 .add(ModItems.PAINTING_FLOWERSEA_COTTAGE.get())
//$$                 .add(ModItems.PAINTING_FRIENDS_PARTY.get())
//$$                 .add(ModItems.PAINTING_FRUITS_BASKET.get())
//$$                 .add(ModItems.PAINTING_GARDEN_ENTRANCE.get())
//$$                 .add(ModItems.PAINTING_GRAMOPHONE.get())
//$$                 .add(ModItems.PAINTING_GRAVEYARD.get())
//$$                 .add(ModItems.PAINTING_HARVEST.get())
//$$                 .add(ModItems.PAINTING_ISLAND.get())
//$$                 .add(ModItems.PAINTING_KITCHEN_SINK.get())
//$$                 .add(ModItems.PAINTING_KITE.get())
//$$                 .add(ModItems.PAINTING_LEMON_SLICE.get())
//$$                 .add(ModItems.PAINTING_MERMAID.get())
//$$                 .add(ModItems.PAINTING_MILKYWAY.get())
//$$                 .add(ModItems.PAINTING_NIGHT_CAMPFIRE.get())
//$$                 .add(ModItems.PAINTING_PUMPKIN.get())
//$$                 .add(ModItems.PAINTING_RAINBOW_UNICORN.get())
//$$                 .add(ModItems.PAINTING_RESTAURANT.get())
//$$                 .add(ModItems.PAINTING_ROSE_SWING.get())
//$$                 .add(ModItems.PAINTING_SALTED_LEMON.get())
//$$                 .add(ModItems.PAINTING_SCENERY.get())
//$$                 .add(ModItems.PAINTING_SKETCH.get())
//$$                 .add(ModItems.PAINTING_SNOW_HOUSE.get())
//$$                 .add(ModItems.PAINTING_STATIONARY_OBJECTS.get())
//$$                 .add(ModItems.PAINTING_SUMPTUOUS_MEAL.get())
//$$                 .add(ModItems.PAINTING_SUNSET.get())
//$$                 .add(ModItems.PAINTING_TEDDY_BEAR.get())
//$$                 .add(ModItems.PAINTING_TOYS.get())
//$$                 .add(ModItems.PAINTING_TULIP.get())
//$$                 .add(ModItems.PAINTING_URBAN_BEAUTY.get())
//$$                 .add(ModItems.PAINTING_WAVES.get())
//$$                 .add(ModItems.PAINTING_WHEAT_FIELD.get())
//$$                 .add(ModItems.PAINTING_WILDFLOWER_PLAIN.get())
//$$                 .add(ModItems.PAINTING_WORLD_TREE.get());
//$$
//$$         getOrCreateTagBuilder(ModItemTags.PHOTO_PAPERS)
//$$                 .add(ModItems.PHOTO_PAPER_WHITE_A.get())
//$$                 .add(ModItems.PHOTO_PAPER_WHITE_B.get())
//$$                 .add(ModItems.PHOTO_PAPER_WHITE_C.get())
//$$                 .add(ModItems.PHOTO_PAPER_BLACK_A.get())
//$$                 .add(ModItems.PHOTO_PAPER_BLACK_B.get())
//$$                 .add(ModItems.PHOTO_PAPER_BLACK_C.get());
//$$
//$$         getOrCreateTagBuilder(ModItemTags.TYPE_A_PHOTO_PAPERS)
//$$                 .add(ModItems.PHOTO_PAPER_WHITE_A.get())
//$$                 .add(ModItems.PHOTO_PAPER_BLACK_A.get());
//$$
//$$         getOrCreateTagBuilder(ModItemTags.TYPE_B_PHOTO_PAPERS)
//$$                 .add(ModItems.PHOTO_PAPER_WHITE_B.get())
//$$                 .add(ModItems.PHOTO_PAPER_BLACK_B.get());
//$$
//$$         getOrCreateTagBuilder(ModItemTags.TYPE_C_PHOTO_PAPERS)
//$$                 .add(ModItems.PHOTO_PAPER_WHITE_C.get())
//$$                 .add(ModItems.PHOTO_PAPER_BLACK_C.get());
//$$     }
//$$ }
//$$
//#endif