/*
 * XHeYa's Furniture (xhe_furniture) - All Rights Reserved
 *
 * Copyright (C) 2026 owen233666, XHeYa_3u3
 */
// Generated by `runDatagen` (see common.gradle). Mirrors the hand-written recipes under
// src/main/resources/data/xhe_furniture/recipe; keep both in sync when editing by hand.
//
// The version dependent parts are expressed as sibling top level conditions instead of nested
// ones: a `//#if` nested inside another `//#if` would need a `//$$` of its own, which makes the
// intent unreadable. 1.20.5 changed the recipe exporter to RecipeOutput, moved the unlock
// condition to Criterion and added the registry lookup future to the provider constructor.
//#if FABRIC
//$$ package com.owen233666.datagen;
//$$
//$$ import com.owen233666.block.ModBlocks;
//$$ import com.owen233666.item.ModItems;
//$$ import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
//$$ import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider;
//$$ import net.minecraft.data.recipes.RecipeCategory;
//$$ import net.minecraft.data.recipes.ShapedRecipeBuilder;
//$$ import net.minecraft.data.recipes.ShapelessRecipeBuilder;
//$$ import net.minecraft.tags.ItemTags;
//$$ import net.minecraft.tags.TagKey;
//$$ import net.minecraft.world.item.Item;
//$$ import net.minecraft.world.item.Items;
//$$ import net.minecraft.world.level.ItemLike;
//#endif
//#if FABRIC && MC >= 12005
//$$ import net.minecraft.advancements.Criterion;
//$$ import net.minecraft.core.HolderLookup;
//$$ import net.minecraft.data.recipes.RecipeOutput;
//$$
//$$ import java.util.concurrent.CompletableFuture;
//#endif
//#if FABRIC && MC < 12005
//$$ import net.minecraft.advancements.CriterionTriggerInstance;
//$$ import net.minecraft.data.recipes.FinishedRecipe;
//$$
//$$ import java.util.function.Consumer;
//#endif
//#if FABRIC
//$$
//$$ public class ModRecipeProvider extends FabricRecipeProvider {
//#endif
//#if FABRIC && MC >= 12005
//$$
//$$     public ModRecipeProvider(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
//$$         super(output, registriesFuture);
//$$     }
//$$
//$$     @Override
//$$     public void buildRecipes(RecipeOutput exporter) {
//$$         buildKitRecipes(exporter);
//$$         buildSingleItemRecipes(exporter);
//$$     }
//$$
//$$     private void buildKitRecipes(RecipeOutput exporter) {
//#endif
//#if FABRIC && MC < 12005
//$$
//$$     public ModRecipeProvider(FabricDataOutput output) {
//$$         super(output);
//$$     }
//$$
//$$     @Override
//$$     public void buildRecipes(Consumer<FinishedRecipe> exporter) {
//$$         buildKitRecipes(exporter);
//$$         buildSingleItemRecipes(exporter);
//$$     }
//$$
//$$     private void buildKitRecipes(Consumer<FinishedRecipe> exporter) {
//#endif
//#if FABRIC
//$$         shaped(exporter, ModItems.SLIPPER_KIT.get(), has(ItemTags.WOOL),
//$$                 new Object[]{'W', ItemTags.WOOL},
//$$                 "WWW", " WW");
//$$
//$$         shaped(exporter, ModItems.CARPET_KIT.get(), has(ItemTags.WOOL),
//$$                 new Object[]{'W', ItemTags.WOOL},
//$$                 "WW", "WW");
//$$
//$$         shaped(exporter, ModItems.SHOE_FLOWER_POT_KIT.get(), has(Items.FLOWER_POT),
//$$                 new Object[]{'W', ItemTags.WOOL, 'P', Items.FLOWER_POT},
//$$                 "W W", "P P");
//$$
//$$         shaped(exporter, ModItems.PAINTING_FRAME_KIT.get(), has(ItemTags.PLANKS),
//$$                 new Object[]{'P', ItemTags.PLANKS},
//$$                 "PPP", "P P", "PPP");
//$$
//$$         shaped(exporter, ModItems.GRID_SHELF_KIT.get(), has(ItemTags.PLANKS),
//$$                 new Object[]{'P', ItemTags.PLANKS, 'S', Items.STICK},
//$$                 "PPP", "SSS");
//$$
//$$         shaped(exporter, ModItems.FURNITURE_CRAFTING_TABLE_KIT.get(), has(ItemTags.PLANKS),
//$$                 new Object[]{'P', ItemTags.PLANKS, 'S', Items.STICK},
//$$                 "PPP", "P P", "SSS");
//$$
//$$         shaped(exporter, ModItems.CORK_BOARD_KIT.get(), has(Items.BROWN_WOOL),
//$$                 new Object[]{'P', ItemTags.PLANKS, 'C', Items.BROWN_WOOL},
//$$                 "PPP", "PCP", "PPP");
//$$
//$$         shapeless(exporter, ModItems.PHOTO_PAPER_KIT.get(), has(Items.BLACK_DYE),
//$$                 Items.PAPER, Items.PAPER, Items.PAPER, Items.PAPER, Items.BLACK_DYE);
//$$
//$$         shaped(exporter, ModItems.PAINTING_KIT.get(), has(Items.WHITE_WOOL),
//$$                 new Object[]{'P', Items.PAPER, 'W', Items.WHITE_WOOL},
//$$                 "PPP", "PWP", "PPP");
//$$     }
//$$
//#endif
//#if FABRIC && MC >= 12005
//$$     private void buildSingleItemRecipes(RecipeOutput exporter) {
//#endif
//#if FABRIC && MC < 12005
//$$     private void buildSingleItemRecipes(Consumer<FinishedRecipe> exporter) {
//#endif
//#if FABRIC
//$$         shapeless(exporter, ModBlocks.HOT_COCOA.get().asItem(), has(Items.COCOA_BEANS),
//$$                 Items.GLASS_BOTTLE, Items.COCOA_BEANS, Items.SUGAR, Items.MILK_BUCKET);
//$$
//$$         shaped(exporter, ModBlocks.RATTAN_TABLE.get().asItem(), has(Items.BAMBOO),
//$$                 new Object[]{'B', Items.BAMBOO, 'S', Items.STICK},
//$$                 "BBB", " B ", " S ");
//$$
//$$         shaped(exporter, ModBlocks.EASEL.get().asItem(), has(Items.STICK),
//$$                 new Object[]{'S', Items.STICK},
//$$                 "S S", "SSS", "S S");
//$$
//$$         shaped(exporter, ModBlocks.CANVAS.get().asItem(), has(Items.WHITE_WOOL),
//$$                 new Object[]{'P', ItemTags.PLANKS, 'W', Items.WHITE_WOOL},
//$$                 "PPP", "PWP", "PPP");
//$$
//$$         ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, ModBlocks.CANVAS_BIG.get().asItem())
//$$                 .define('C', ModBlocks.CANVAS.get())
//$$                 .pattern("CC")
//$$                 .pattern("CC")
//$$                 .unlockedBy("has_canvas", has(ModBlocks.CANVAS.get()))
//$$                 .save(exporter);
//$$
//$$         shaped(exporter, ModBlocks.DRAWING_BOARD.get().asItem(), has(Items.PAPER),
//$$                 new Object[]{'P', ItemTags.PLANKS, 'W', Items.PAPER},
//$$                 "PPP", "PWP", "PPP");
//$$
//$$         shaped(exporter, ModItems.PAINT_BRUSH.get(), has(Items.STICK),
//$$                 new Object[]{'W', Items.WHITE_WOOL, 'S', Items.STICK},
//$$                 "W", "S");
//$$
//$$         shaped(exporter, ModBlocks.PAINT_CAN.get().asItem(), has(Items.IRON_INGOT),
//$$                 new Object[]{'I', Items.IRON_INGOT},
//$$                 "II", "II", "II");
//$$
//$$         shapeless(exporter, ModBlocks.MESSY_PAINT_CAN.get().asItem(), has(ModBlocks.PAINT_CAN.get()),
//$$                 ModBlocks.PAINT_CAN.get(), Items.BLACK_DYE);
//$$
//$$         shapeless(exporter, ModBlocks.PAINT_BRUSH_BUCKET.get().asItem(), has(Items.BUCKET),
//$$                 Items.BUCKET, ModItems.PAINT_BRUSH.get());
//$$
//$$         shapeless(exporter, ModBlocks.OPEN_BOOK.get().asItem(), has(Items.PAPER),
//$$                 Items.PAPER, Items.PAPER, Items.PAPER, Items.LEATHER);
//$$
//$$         shaped(exporter, ModBlocks.CRAYON_BOX.get().asItem(), has(ItemTags.PLANKS),
//$$                 new Object[]{'P', ItemTags.PLANKS, 'W', Items.PAPER},
//$$                 "PPP", "PWP", "PPP");
//$$
//$$         shaped(exporter, ModBlocks.PALETTE.get().asItem(), has(ItemTags.PLANKS),
//$$                 new Object[]{'P', ItemTags.PLANKS, 'W', Items.WHITE_WOOL},
//$$                 "PW", "PP");
//$$     }
//$$
//#endif
//#if FABRIC && MC >= 12005
//$$     private void shaped(RecipeOutput exporter, ItemLike result, Criterion<?> unlock,
//$$                         Object[] keyed, String... pattern) {
//#endif
//#if FABRIC && MC < 12005
//$$     private void shaped(Consumer<FinishedRecipe> exporter, ItemLike result, CriterionTriggerInstance unlock,
//$$                         Object[] keyed, String... pattern) {
//#endif
//#if FABRIC
//$$         ShapedRecipeBuilder builder = ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, result);
//$$         for (String row : pattern) {
//$$             builder.pattern(row);
//$$         }
//$$         for (int i = 0; i < keyed.length; i += 2) {
//$$             char key = (Character) keyed[i];
//$$             Object value = keyed[i + 1];
//$$             if (value instanceof TagKey<?> tag) {
//$$                 builder.define(key, (TagKey<Item>) tag);
//$$             } else {
//$$                 builder.define(key, (ItemLike) value);
//$$             }
//$$         }
//$$         builder.unlockedBy("has_material", unlock).save(exporter);
//$$     }
//$$
//#endif
//#if FABRIC && MC >= 12005
//$$     private void shapeless(RecipeOutput exporter, ItemLike result, Criterion<?> unlock,
//$$                            ItemLike... ingredients) {
//#endif
//#if FABRIC && MC < 12005
//$$     private void shapeless(Consumer<FinishedRecipe> exporter, ItemLike result, CriterionTriggerInstance unlock,
//$$                            ItemLike... ingredients) {
//#endif
//#if FABRIC
//$$         ShapelessRecipeBuilder builder = ShapelessRecipeBuilder.shapeless(RecipeCategory.DECORATIONS, result);
//$$         for (ItemLike ingredient : ingredients) {
//$$             builder.requires(ingredient);
//$$         }
//$$         builder.unlockedBy("has_material", unlock).save(exporter);
//$$     }
//$$ }
//#endif
