# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod Properties
mod_id=template_mod
mod_name=TemplateMod
mod_version=1.0.0
maven_group=me.fallenbreath
archives_base_name=template_mod

# Global Dependencies
# https://github.com/Fallen-Breath/conditional-mixin
#	conditionalmixin_version=0.6.4

# https://github.com/LlamaLad7/MixinExtras
#	mixinextras_version=0.3.6
