# Gradle Properties
	org.gradle.jvmargs=-Xmx6G

# Mod Properties
	mod_id=xhe_furniture
	mod_name=XHeYa's Furniture
	mod_version=1.0.0-snapshot4
	maven_group=me.fallenbreath
	archives_base_name=xhe_furniture

# Global Dependencies
	# https://github.com/Fallen-Breath/conditional-mixin
#	conditionalmixin_version=0.6.4

	# https://github.com/LlamaLad7/MixinExtras
#	mixinextras_version=0.3.6
