modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/owen233666/xhe_furniture/issues"

[[mods]]
modId="xhe_furniture"
version="${version}"
displayName="XHeYa's Furniture"
logoFile="icon.png"
description='''感谢下载小禾家具，如遇BUG请前往模组发布页面反馈~'''
authors="owen233666, XHeYa_3u3"
displayTest="MATCH_VERSION"

[[dependencies.xhe_furniture]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.xhe_furniture]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="xhe_furniture.mixins.json"
